version: '3'
services:
  web:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
