FROM node:14 as frontend-builder

WORKDIR /app

COPY client/package*.json ./

RUN npm install

COPY client/ ./

RUN npm run build

FROM python:3.9 as backend

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY server/ ./

EXPOSE 5000

ENV FLASK_APP=app.py
ENV FLASK_ENV=production

CMD ["flask", "run", "--host=0.0.0.0"]

FROM nginx:alpine

COPY --from=frontend-builder /app/build /usr/share/nginx/html

COPY --from=backend /app /app

EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]
