services:
  - type: web
    name: ml-backend
    env: python
    buildCommand: 'pip install -r server/requirements.txt'
    startCommand: 'gunicorn server.app:app --bind 0.0.0.0:5000'
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    plan: free
    autoDeploy: true
    healthCheckPath: '/'

  - type: web
    name: ml-frontend
    env: node
    buildCommand: 'npm install && npm run build'
    startCommand: 'serve -s build'
    staticPublishPath: client/build
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
